// Copyright 2024 The go-ethereum Authors
// This file is part of go-ethereum.
//
// go-ethereum is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// go-ethereum is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with go-ethereum. If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/ethereum/go-ethereum/tests/fuzzers/statetest"
	"github.com/urfave/cli/v2"
)

var statsCommand = &cli.Command{
	Name:      "stats",
	Usage:     "Show statistics about a corpus",
	ArgsUsage: "<corpus-dir>",
	Action:    statsAction,
	Flags:     statsFlags,
	Description: `
The stats command analyzes a corpus directory and reports statistics
about the test files, including fork distribution, trace line counts,
and metadata coverage.

Example usage:
  statetest-trace stats ./enhanced_corpus
  statetest-trace stats --json ./enhanced_corpus
`,
}

func statsAction(ctx *cli.Context) error {
	if ctx.NArg() < 1 {
		return fmt.Errorf("usage: statetest-trace stats <corpus-dir>")
	}

	corpusDir := ctx.Args().Get(0)
	jsonOutput := ctx.Bool(JSONFlag.Name)
	quiet := ctx.Bool(QuietFlag.Name)

	// Try to load manifest first
	manifestPath := filepath.Join(corpusDir, "manifest.json")
	manifest, manifestErr := statetest.LoadManifest(manifestPath)

	// Gather corpus stats
	stats, err := statetest.GatherCorpusStats(corpusDir)
	if err != nil {
		return fmt.Errorf("gather stats: %w", err)
	}

	// Output
	if jsonOutput {
		output := struct {
			Manifest *statetest.Manifest     `json:"manifest,omitempty"`
			Stats    *statetest.CorpusStats  `json:"stats"`
		}{
			Stats: stats,
		}
		if manifestErr == nil {
			output.Manifest = manifest
		}

		data, err := json.MarshalIndent(output, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal JSON: %w", err)
		}
		fmt.Println(string(data))
		return nil
	}

	if quiet {
		return nil
	}

	// Human-readable output
	fmt.Println("========================================")
	fmt.Println("Corpus Statistics")
	fmt.Println("========================================")
	fmt.Printf("Directory:      %s\n", corpusDir)
	fmt.Println()

	// Manifest info if available
	if manifestErr == nil {
		fmt.Println("--- Manifest ---")
		fmt.Printf("Generated At:   %s\n", manifest.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))
		fmt.Printf("Generated By:   %s\n", manifest.GeneratedBy)
		fmt.Printf("Geth Version:   %s\n", manifest.GethVersion)
		fmt.Printf("Processing:     %s with %d workers\n", manifest.ProcessingTime, manifest.Workers)
		fmt.Println()
	}

	// File counts
	fmt.Println("--- File Counts ---")
	fmt.Printf("Total Files:    %d\n", stats.TotalFiles)
	fmt.Printf("Valid Tests:    %d\n", stats.ValidTests)
	fmt.Printf("Invalid Tests:  %d\n", stats.InvalidTests)
	fmt.Printf("With Metadata:  %d\n", stats.WithMetadata)
	fmt.Println()

	// Trace line stats
	if stats.WithMetadata > 0 {
		fmt.Println("--- Trace Lines ---")
		fmt.Printf("Min:     %d\n", stats.MinTraceLines)
		fmt.Printf("Max:     %d\n", stats.MaxTraceLines)
		fmt.Printf("Average: %.1f\n", stats.AvgTraceLines)
		fmt.Println()
	}

	// Fork distribution
	if len(stats.ForkCounts) > 0 {
		fmt.Println("--- Fork Distribution ---")

		// Sort forks by count (descending)
		type forkCount struct {
			fork  string
			count int
		}
		var forks []forkCount
		for fork, count := range stats.ForkCounts {
			forks = append(forks, forkCount{fork, count})
		}
		sort.Slice(forks, func(i, j int) bool {
			return forks[i].count > forks[j].count
		})

		for _, fc := range forks {
			pct := float64(fc.count) / float64(stats.WithMetadata) * 100
			fmt.Printf("%-12s %5d (%.1f%%)\n", fc.fork+":", fc.count, pct)
		}
		fmt.Println()
	}

	// Timestamps
	if !stats.OldestFile.IsZero() {
		fmt.Println("--- Time Range ---")
		fmt.Printf("Oldest: %s\n", stats.OldestFile.Format("2006-01-02 15:04:05 UTC"))
		fmt.Printf("Newest: %s\n", stats.NewestFile.Format("2006-01-02 15:04:05 UTC"))
		fmt.Println()
	}

	fmt.Println("========================================")

	return nil
}

// ListTestsDir is a helper to list test files in a directory
func ListTestsDir(dir string) ([]string, error) {
	var files []string
	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && filepath.Ext(path) == ".json" {
			files = append(files, path)
		}
		return nil
	})
	return files, err
}
